### ISSUE TITLE
该插件会导致Jrebel热部署插件不可用

### ISSUE THREAD

**Issue by Charlee-du** [JTrackerTeam/jtracker4intellij#1]
该插件会导致Jrebel热部署插件不可用，启动项目服务直接报错
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at s\open\src\java.instrument\share\native\libinstrument\JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed

**Comment by pillarcoin** [comment]
同样的问题 关了这个插件就好了
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.instrument/sun.instrument.InstrumentationImpl._jrLoadClassAndStartAgent(InstrumentationImpl.java:491)
	at java.base/com.zeroturnaround.jrebelbase.reorder.b.start(SourceFile:106)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:41001)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:503)
Caused by: java.lang.VerifyError: Stack map does not match the one at exception handler 54
Exception Details:
  Location:
    jtracker/IIiiiIIiiII.add(Ljava/lang/Object;)V @54: aload_2
  Reason:
    Type 'java/lang/Object' (current frame, locals[0]) is not assignable to 'jtracker/IIiiiIIiiII' (stack map, locals[0])
  Current Frame:
    bci: @14
    flags: { }
    locals: { 'java/lang/Object', 'java/lang/Object', 'java/lang/Object' }
    stack: { 'java/lang/Throwable' }
  Stackmap Frame:
    bci: @54
    flags: { }
    locals: { 'jtracker/IIiiiIIiiII', top, 'java/lang/Object' }
    stack: { 'java/lang/Throwable' }
  Bytecode:
    0000000: 1100 0057 2ab8 00dd 594d c22a 2b4b 4c2b
    0000010: b700 2a2a 59b6 007a b800 f1ba 0084 0000
    0000020: b900 8803 0012 0db8 00d5 c000 0d2a 01b6
    0000030: 008c 572c c3b1 2cc3 b800 e8c0 0059 bf  
  Exception Handler Table:
    bci [11, 54] => handler: 54
  Stackmap Table:
    full_frame(@54,{Object[#2],Top,Object[#4]},{Object[#89]})

	at jtracker.IiiIIIIIIIi.<clinit>(ufa)
	at jtracker.IiiiIIiIIII.<init>(kja:455)
	at jtracker.IiiiIIiIIII.<init>(kja:177)
	at jtracker.iiiiiIiIIiI.<clinit>(lda:150)
	at jtracker.iIIIIIIiIIi.IIIiIiIiiiii(hca:6)
	at jtracker.iIIIIIIiIIi.premain(hca:123)
	... 8 more
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message Outstanding error when calling method in invokeJavaAgentMainMethod at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 619
*** java.lang.instrument ASSERTION FAILED ***: "success" with message invokeJavaAgentMainMethod failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 459
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.dylib+0x57f5af]  jni_FatalError+0xdf
V  [libjvm.dylib+0x6e062b]  JvmtiExport::post_vm_initialized()+0x26b
V  [libjvm.dylib+0xaa1e6c]  Threads::create_vm(JavaVMInitArgs*, bool*)+0x8bc
V  [libjvm.dylib+0x5995f5]  JNI_CreateJavaVM+0x65
C  [libjli.dylib+0x4963]  JavaMain+0x113
C  [libjli.dylib+0x79a9]  ThreadJavaMain+0x9
C  [libsystem_pthread.dylib+0x618b]  _pthread_start+0x63
C  [libsystem_pthread.dylib+0x1ae3]  thread_start+0xf

Disconnected from the target VM, address: '127.0.0.1:58473', transport: 'socket'

Process finished with exit code 134 (interrupted by signal 6:SIGABRT)
```
